### ISSUE TITLE
When installed `commands` is not properly setup in `index.js`

### ISSUE THREAD

**Issue by RayBenefield** [nickzuber/add-reason#4]
Just tried setting this up with my project and ran into this:

<img width="630" alt="screen shot 2018-02-09 at 6 13 23 am" src="https://user-images.githubusercontent.com/6372131/36031647-537f5936-0d60-11e8-910a-a10596c598df.png">

Did a bit of digging, noticed that the `commands` import statement is looking for something in `node_modules`, but there is no link to it. So I manually added a relative link to the compiled version that was distributed and it worked fine. So something with the build/distribution process of this needs a tweak to make it work properly from install. :) Hope this helps.

<img width="1440" alt="screen shot 2018-02-09 at 6 12 20 am" src="https://user-images.githubusercontent.com/6372131/36031712-8a746a4e-0d60-11e8-8581-6f161c744267.png">

Also thanks for setting this up. :) I've been working on a unique monorepo setup and tried a babel-plugin last night for bucklescript that didn't really work as expected, but this worked fine for my experimentation purposes at least. I've been wanting to get into [**ReasonML**](https://reasonml.github.io/), but getting it tied into my monorepo setup was a pain, but this definitely worked great. Haven't tested my publish system, but the build system seems to have picked up the compiled code neatly on local. So as long as it `yarn`'s properly on CI, my publish system should pick it up as well. :) Excited to start playing with some [**ReasonML**](https://reasonml.github.io/) here and there.

**Comment by nickzuber** [comment]
Hey Ray, thanks for finding this! Yeah the issue was I somehow lost the postinstall script on this package that hooks up that symlink, it should be fixed now 😄

**Comment by nickzuber** [comment]
I'm going to close this issue since I'm pretty sure it's been resolved -- if anyone else runs into this problem I can reopen
