### ISSUE TITLE
Fresh install fails: no such file or directory

### ISSUE THREAD

**Issue by gaelduplessix** [nickzuber/add-reason#5]
Hey there ! I had an error trying to install `add-reason`:
![image](https://user-images.githubusercontent.com/2292908/36075016-79661704-0f48-11e8-9e2e-09a10a2e0a14.png)

I'm using node `v8.9.3`. Any idea what may be going wrong ?

Thx :)

**Comment by nickzuber** [comment]
Hey Gael, thanks for finding this! Looks like another symlink issue, I just published a new version with a patch with a fix -- let me know if that works for you!

**Comment by nickzuber** [comment]
Closing this because it seems to have been fixed

**Comment by gaelduplessix** [comment]
Re-tested and works like a charm, thx :) 

Little feedback from my test: still feels a bit weird that I have to run `bsb -make-world` myself. If the target users for this project is reason beginners, it could make sense to automate this in some way. 
Maybe adding a `build-reason` in `package.json` scripts. Also, I had to manually link `bs-platform`.
If those steps were automated, it would become a no-brainer for dropping Reason into an existing js project, which is awesome 👍

**Comment by nickzuber** [comment]
@gaelduplessix thanks for the feedback! I agree, the process would be much smoother with being able to link `bs-platform` and or handling that in some way (notifying user that is isn't linked if it's not found in `node_modules`). 

There some discussion on adding similar behavior to [`bs-platform` itself](https://github.com/BuckleScript/bucklescript/issues/2500) which would be awesome especially for beginners (avoiding this divergence in tools). I plan on picking this issue up once theres more solidified direction!

In the mean time, it would be cool if we could add another step, perhaps during the `postinstall` step that adds a `build-reason` command to the package.json file which simply calls `bsb -make-world`.

```json
"scripts": {
  "build-reason": "bsb -make-world",
  "postinstall": "..."
}
```

Additionally, there can be another final step that simply checks `node_modules` to see if `bs-platform` exists, and if not then prompt the user to `npm link bs-platform` or `npm install -g bs-platform`.

Both changes should be really easy and quick to implement and would make things a lot easier to work with -— I'm a little busy with school work at the moment so I could pick this up once my work load dies down, or if you wanted to make an issues/pull request for this that'd be awesome too 😄
